### ISSUE TITLE
WxMaxima does not compile on FreeBSD-9.3-RELEASE

### ISSUE THREAD

**Issue by nivit** [andrejv/wxmaxima#406]
Hi,

as title says, I get the following error when compiling wxMaxima on FreeBSD-9.3-RELEASE:

    MathCtrl.cpp: In member function 'void MathCtrl::SelectWithChar(wxChar)': 
    MathCtrl.cpp:1580: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: 
    MathCtrl.cpp:1580: note: candidate 1: operator==(int, int) <built-in> /usr/local/include/wx-2.8/wx/string.h:1633: note: candidate 2: bool operator==(wxChar, const wxString&) 
    MathCtrl.cpp:1580: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: 
    MathCtrl.cpp:1580: note: candidate 1: operator==(int, int) <built-in>

[Full Log](http://beefy1.isc.freebsd.org/data/93i386-default/2015-02-04_20h08m24s/logs/wxMaxima-14.12.1.log)

it compiles without errors on other OS versions.

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Unfortunately I don't even get a warning here so I cannot test too
much. But Wolfgang's nightly builds show the same message as a warning.

What seems to be the problem is that this function compares the wxChar
ccode with an enum that has values like WXK_DOWN...
...the examples on wxwidgets.org seem happily to mix the enum with int
with wxChar so it is hard to find out what should be the right behavior.

Kind regards,

 Gunter.


On 05.02.2015 11:21, Nicola Stanislao Vitale wrote:
> Hi,
> 
> as title says, I get the following error when compiling wxMaxima
> on FreeBSD-9.3-RELEASE:
> 
> |MathCtrl.cpp: In member function 'void
> MathCtrl::SelectWithChar(wxChar)': MathCtrl.cpp:1580: error: ISO
> C++ says that these are ambiguous, even though the worst conversion
> for the first is better than the worst conversion for the second: 
> MathCtrl.cpp:1580: note: candidate 1: operator==(int, int)
> <built-in> /usr/local/include/wx-2.8/wx/string.h:1633: note:
> candidate 2: bool operator==(wxChar, const wxString&) 
> MathCtrl.cpp:1580: error: ISO C++ says that these are ambiguous,
> even though the worst conversion for the first is better than the
> worst conversion for the second: MathCtrl.cpp:1580: note: candidate
> 1: operator==(int, int) <built-in> |
> 
> Full Log 
> <http://beefy1.isc.freebsd.org/data/93i386-default/2015-02-04_20h08m24s/logs/wxMaxima-14.12.1.log>
>
>  it compiles without errors on other OS versions.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/andrejv/wxmaxima/issues/406>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQJ8BAEBCgBmBQJU01eiXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOAjwQAIUs6orAgkHVgK/8iPMREhL8
hStrcPQc8S7HgCRHlB34pe1oZqTVJhwYmdI5cR/sEzFgb0A/Tt0EMgKKkzGAiVsd
2BM8jO4j1wM6fK1R2fKZdFYka9r+tUsBMf6vwu0+ktZhhz34mZlZCi7nfwZg8ENh
LArhqsqMAJ3491BER74O+vR3Ouen6k/5i0A9lIhDUCNwMNVYe2+k9EDAKUO08dd/
c+46fgWqJAY+sJbbooUBVCiWr6IXyy3dZP+G4uNzOV46b12I1nJjsIpa1FBinRQc
QVeJVlaMDJzQYLmJPyD6qSlbz2FOjc0lcnLHh/By235WhMmAdiZq1gVfklPpmSka
VbhznCKOqX6wZqPOQvE7XRPi8dXyKOJT4kcIqryCiZw9ApvjpdZF6lWbqkSe0QL4
IvKtV3yf/f3OcEU2DEMk31bFhT3vOkM+haBRYBLJkJ1HbJdniMrW/YbFHaVMKPyX
SFS9NowKnwKQXHy6XAilM52qY0Jr9cHLVW7EXldXB+lX2CSR2NWjeQE0bmQfAc8y
sp+i4IW1EzYR7ghGPTaV3Ugq4Qi/FXpm42j+P3zto/XL3YUO8zDQ7GAgPrn6fe/E
QNP2Ku/Ei7MT6eXz2BAQRTwwgRTkv7+QccZDaPspWt1cdxYcIoOWeH1sE8B3uSZp
Qkxj4NKiUb4f+0GYo2Ob
=Wj5+
-----END PGP SIGNATURE-----

**Comment by andrejv** [comment]
Should be fixed in 483155a. Let me know if you would like a patch against 14.12.1.

BTW, wxmaxima does not depend on libxml2 anymore.

**Comment by nivit** [comment]
I have updated the FreeBSD port with your patches (removing also libxml2), and now it compiles perfectly. Thank you very much!
